apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/termproject-default: "true"
        io.kompose.service: api-gateway
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - npx prisma migrate dev && yarn start
          env:
            - name: CHAT_BASE_URL
              value: chat-service:30043
            - name: DATABASE_URL
              value: postgresql://postgres:123@api-db:5432/api
            - name: JWT_SECRET
              value: super-secret
            - name: ORGANIZE_BASE_URL
              value: http://organize-service:5003
            - name: PORT
              value: "3333"
            - name: PROFILE_BASE_URL
              value: http://profile-service:5004
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672/
          image: chainecs/api-gateway-img:latest
          name: api-gateway
          ports:
            - containerPort: 3333
              hostPort: 3333
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
