version: "3"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=P@ssw0rd
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge
