apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: organize-service
  name: organize-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: organize-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/termproject-default: "true"
        io.kompose.service: organize-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: organize-db
            - name: DB_NAME
              value: organizeDB
            - name: DB_PASSWORD
              value: "123"
            - name: DB_PORT
              value: "5432"
            - name: DB_SSLMODE
              value: disable
            - name: DB_TIMEZONE
              value: Asia/Bangkok
            - name: DB_USER
              value: postgres
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672/
          image: chainecs/organize-img:latest
          name: organize-service
          ports:
            - containerPort: 5003
              hostPort: 5003
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
