version: '3.8'
services:
  organize:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: organizeDB
    networks:
      - chainlocalnetwork
  
 #### รัน organize-service ด้วย 
  organize-service:
    image: chainecs/organize-img:latest
    ports:
      - 8081:8080
    depends_on:
      - organize
    environment:
      DB_HOST: organize #เปลี่ยนจาก localhost เป็น organize เพราะจะรันสองเซอวิสพร้อมกัน
      DB_PORT: 5432 #ใช้ 5432 แทน 5436 เพราะว่าเป็นการคุยกันใน docker
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: organizeDB
      DB_SSLMODE: disable
      DB_TIMEZONE: Asia/Bangkok
      RABBITMQ_URL: amqp://guest:guest@localhost:5672/
    networks:
      - chainlocalnetwork

networks:
  chainlocalnetwork:
